version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.50.0
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y libssl-dev
      - run: cargo --version
      - run:
          name: Run Tests
          command: |
            cargo test
